# Global configuration
spring.application.name=mdd

# Server configuration
server.port=3001

# MySQL Database configuration
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# LOGGER 
logging.level.root=INFO
logging.level.com.orion=INFO

# JWT configuration
oc.app.jwtSecret=${JwtKey}
oc.app.jwtExpirationMs=7200000



